name: Lint and test package
description: Runs the entire suite of CI steps on a given package

inputs:
  package-name:
    description: The name of the package
    required: true

runs:
  using: "composite"
  steps:
    - uses: pnpm/action-setup@v2
      with:
        version: 7
    - uses: actions/setup-node@v3
      with:
        node-version: 18
        cache: "pnpm"
    - run: pnpm install
      shell: bash
    - name: Linting
      run: pnpm ci-lint
      working-directory: packages/${{ inputs.package-name }}
      shell: bash
      continue-on-error: true
    - name: Test
      run: pnpm ci-test
      working-directory: packages/${{ inputs.package-name }}
      shell: bash
