name: Tests
on: push

jobs:
  interpreter:
    name: Interpreter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - name: Lint and test
        uses: ./.github/actions/lint-and-test
        with:
          package-name: interpreter
