name: Tests
on: push

jobs:
  interpreter:
    name: Interpreter
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
      - uses: pnpm/action-setup@v2
        with:
          version: 7
      - uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: "pnpm"
      - run: pnpm install
      - name: Linting
        run: pnpm ci-lint
        working-directory: packages/interpreter
        continue-on-error: true
      - name: Test
        run: pnpm ci-test
        working-directory: packages/interpreter
