name: Tests
on: push

jobs:
  interpreter:
    name: Interpreter
    runs-on: ubuntu-latest
    steps:
      - uses: ./.github/actions/setup
      - run: |
          pnpm install
          cd packages/interpreter
          pnpm ci-test
